/*
  © [2011]. California Institute of Technology. 
  ALL RIGHTS RESERVED. U.S. Government sponsorship acknowledged.  
  Any commercial use must be negotiated with the Office of Technology 
  Transfer at the California Institute of Technology. The technical data in 
  this document is controlled under the U.S. Export Regulations, release to 
  foreign persons may require an export authorization.
*/

package tracecontract

/**
 * Messages are produced by calls of the methods <code>ok(message: String)</code> and
 * <code>error(message: String)</code>. Such messages are stored in - and are accessible from -
 * the <code>PropertyResult</code> object associated with each property. A field indicates
 * whether the message was produced by a call of <code>ok</code> or <code>error</code>.
 * 
 * @param ok is true if the message was generated by a call of the <code>ok(message: String)</code> method
 * and  false if generated with a call of the <code>error(message: String)</code> method.
 */
case class Message(ok: Boolean, message: String) {
  override def toString: String = {
    var result = if (ok) "!!! ok:" else "*** error:"
    result + " " + message + "\n"
  }
}
